### ISSUE TITLE
[BUG] AttributeError: 'IPSkill' object has no attribute '_settings_path'

### ISSUE THREAD

**Issue by goldyfruit** [NeonGeckoCom/skill-ip_address#45]
### Description

Unable to install the skill on OVOS.

Here is the trace:

```
2023-10-24 13:26:52.438 - skills - ovos_workshop.skill_launcher:load:528 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: skill-ip_address.neongeckocom
2023-10-24 13:26:52.450 - skills - ovos_workshop.skill_launcher:_create_skill_instance:456 - WARNING - Skill load raised exception: Expected module and got None
2023-10-24 13:26:52.463 - skills - ovos_workshop.skills.mycroft_skill:MycroftSkill.__init__ - WARNING - Deprecation version=0.1.0. Caller=ovos_workshop.decorators.compat:40. MycroftSkill class has been deprecated, please subclass from OVOSSkill
2023-10-24 13:26:52.474 - skill-ip_address.neongeckocom - ERROR - Skill initialization failed
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 715, in _startup
    self._init_settings()
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/skills/mycroft_skill.py", line 70, in _init_settings
    skill_settings = get_local_settings(self._settings_path)
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'IPSkill' object has no attribute '_settings_path'
2023-10-24 13:26:52.486 - skills - ovos_workshop.skill_launcher:_create_skill_instance:476 - WARNING - Legacy skill: 'IPSkill' object has no attribute '_settings_path'
2023-10-24 13:26:52.493 - skills - ovos_workshop.skills.mycroft_skill:__call__:71 - WARNING - skill initialized without bus!! this is legacy behaviour and requires you to call skill.bind(bus) or skill._startup(skill_id, bus)
bus will be required starting on ovos-core 0.1.0
2023-10-24 13:26:52.502 - skills - ovos_workshop.skills.mycroft_skill:MycroftSkill.__init__ - WARNING - Deprecation version=0.1.0. Caller=ovos_workshop.decorators.compat:40. MycroftSkill class has been deprecated, please subclass from OVOSSkill
2023-10-24 13:26:52.516 - skills - ovos_workshop.skill_launcher:_create_skill_instance:484 - WARNING - Deprecation version=0.1.0. Caller=ovos_core.skill_manager:360. This initialization is deprecated. Update skill tohandle passed `skill_id` and `bus` kwargs
2023-10-24 13:26:52.520 - skill-ip_address.neongeckocom - ERROR - Skill initialization failed
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 715, in _startup
    self._init_settings()
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/skills/mycroft_skill.py", line 70, in _init_settings
    skill_settings = get_local_settings(self._settings_path)
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'IPSkill' object has no attribute '_settings_path'
2023-10-24 13:26:52.522 - skill-ip_address.neongeckocom - WARNING - Skill not fully initialized.to correct this add kwargs __init__(bus=None, skill_id='') to skill class IPSkill
2023-10-24 13:26:52.523 - skill-ip_address.neongeckocom - ERROR - Traceback:
  File "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_core/skill_manager.py", line 313, in handle_internet_connected
    self._load_on_internet()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_core/skill_manager.py", line 487, in _load_on_internet
    self._load_new_skills(network=True, internet=True)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_core/skill_manager.py", line 548, in _load_new_skills
    self.load_plugin_skills(network=network, internet=internet)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_core/skill_manager.py", line 336, in load_plugin_skills
    self._load_plugin_skill(skill_id, plug)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_core/skill_manager.py", line 360, in _load_plugin_skill
    load_status = skill_loader.load(skill_plugin)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 532, in load
    return self._load()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 544, in _load
    self.loaded = self._create_skill_instance()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 488, in _create_skill_instance
    self.instance._startup(self.bus, self.skill_id)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 735, in _startup
    self.default_shutdown()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 1184, in default_shutdown
    self.bus.emit(

2023-10-24 13:26:52.544 - skills - ovos_workshop.skill_launcher:_create_skill_instance:490 - ERROR - Skill __init__ failed with 'IPSkill' object has no attribute '_settings_path'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 488, in _create_skill_instance
    self.instance._startup(self.bus, self.skill_id)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 738, in _startup
    raise e
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/ovos.py", line 715, in _startup
    self._init_settings()
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/skills/mycroft_skill.py", line 70, in _init_settings
    skill_settings = get_local_settings(self._settings_path)
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'IPSkill' object has no attribute '_settings_path'
2023-10-24 13:26:52.558 - skills - ovos_workshop.skill_launcher:_communicate_load_status:513 - ERROR - Skill skill-ip_address.neongeckocom failed to load
2023-10-24 13:26:58.405 - skills - ovos_core.intent_services.padatious_service:train:144 - INFO - Training complete.

```

**Comment by NeonDaniel** [comment]
I see I [added some handling](https://github.com/NeonGeckoCom/neon-utils/compare/1.6.2...1.6.3a3#diff-a0c3f5e440e697e5c3d0115e8989c6b036f84436d46d2eba39be600743f53a25R61) to one of the more recent alpha releases of `neon-utils`. Let me look into how much of this patching is still necessary and try to get those changes into a stable `neon-utils` release

**Comment by NeonDaniel** [comment]
This is related to changes in the latest ovos-workshop alpha releases being incompatible with some of the patching in Neon. I think this is fixed in the latest pre-release version of [neon-utils](https://github.com/NeonGeckoCom/neon-utils) but I have to do some more backwards-compat. testing. `pip install --upgrade neon-utils --pre` should resolve this specific issue for now
